version: '3'
services:
  postgres:
    build:
      context: ./docker/
      dockerfile: pg-docker
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: